### ISSUE TITLE
Can't run on Snow Leopard

### ISSUE THREAD

**Issue by senderista** [plessl/wkpdf#10]
Even after installing the latest version, wkpdf barfs with this message:

$ sudo gem update --system
$ sudo gem install plessl-wkpdf --source http://gems.github.com
$ wkpdf --help

Platform not supported: wkpdf runs only on Mac OS X 10.5 and later

$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.6.1
BuildVersion:   10B504

**Comment by plessl** [comment]
No idea what is going wrong. Could you please post the output of wkpdf --version?

**Comment by plessl** [comment]
Problem has been solved. An additional version of Ruby 1.9 without RubyCocoa was installed that conflicted with the system Ruby.

**Comment by nextofsearch** [comment]
@plessl Can you share how you solved it? I am stucked in the same place. Thanks!
Installing RubyCocoa 1.0.2 didn't solve it.

My env:
ruby 1.9.3-p194
Mac OS 10.7.4

**Comment by plessl** [comment]
I don't know how the problem was solved since this was senderista's problem, not mine.

Is there anything that prevents you from using system ruby?

**Comment by nextofsearch** [comment]
@plessl it's just inconvenience. Switching back and forth between different Ruby versions. I guess it's the way how it goes for now. Thanks!

**Comment by plessl** [comment]
@nextofsearch Regarding switching back an forth between Ruby versions, the tool "rvm" greatly simplifies this task.

One idea that could solve your problem is running wkpdf by specifying your ruby version explicitly.

`/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/ruby /usr/bin/wkpdf arguments`

If this works, you could add a wrapper alias to your shell.

**Comment by nextofsearch** [comment]
Hi @plessl 
I am using rvm already. I will try your suggestion. Thanks!
